"""empty message

Revision ID: 54accc16becb
Revises: 48440e9f77a9
Create Date: 2024-03-03 08:07:22.781310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54accc16becb'
down_revision = '48440e9f77a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
